version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker:/docker-entrypoint-initdb.d

  init-db:
    image: postgres:latest
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./.docker:/docker-entrypoint-initdb.d
    entrypoint: ["/docker-entrypoint-initdb.d/init.sh"]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    ports:
      - "50051:50051"
      - "9091:9091"
    depends_on:
      - postgres
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  http-server:
    build:
      context: .
      dockerfile: Dockerfile.http
    ports:
      - "8080:8080"
    depends_on:
      - grpc-server

volumes:
  postgres_data: