basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Rest API Best Practices
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Say hello
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hello example
      tags:
      - example
  /ping:
    get:
      consumes:
      - application/json
      description: Do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping example
      tags:
      - example
swagger: "2.0"
